import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { v4 as uuidv4 } from 'uuid'
import { resolve } from 'path'

// Manual .env parsing
const envFile = readFileSync(resolve('../.env'), 'utf8')
const env = {}
for (const line of envFile.split('\n')) {
  const m = line.match(/^([^=]+)=(.*)$/)
  if (m) env[m[1].trim()] = m[2].trim()
}

const supabase = createClient(
  env.SUPABASE_URL,
  env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false } }
)

const mappings = `KANIT PAMINAL POLRES BANJAR KOTA POLDA JAWA BARAT|POLRES BANJAR KOTA
KANIT PAMINAL POLRES BOGOR POLDA JAWA BARAT|POLRES BOGOR
KANIT PAMINAL POLRES CIAMIS POLDA JAWA BARAT|POLRES CIAMIS
KANIT PAMINAL POLRES CIANJUR POLDA JAWA BARAT|POLRES CIANJUR
KANIT PAMINAL POLRES CIMAHI POLDA JAWA BARAT|POLRES CIMAHI
KANIT PAMINAL POLRES CIREBON KOTA POLDA JAWA BARAT|POLRES CIREBON KOTA
KANIT PAMINAL POLRES GARUT POLDA JAWA BARAT|POLRES GARUT
KANIT PAMINAL POLRES KARAWANG POLDA JAWA BARAT|POLRES KARAWANG
KANIT PAMINAL POLRES MAJALENGKA POLDA JAWA BARAT|POLRES MAJALENGKA
KANIT PAMINAL POLRES PURWAKARTA POLDA JAWA BARAT|POLRES PURWAKARTA
KANIT PAMINAL POLRES SUBANG POLDA JAWA BARAT|POLRES SUBANG
KANIT PAMINAL POLRES SUKABUMI KOTA POLDA JAWA BARAT|POLRES SUKABUMI KOTA
KANIT PAMINAL POLRES SUKABUMI POLDA JAWA BARAT|POLRES SUKABUMI
KANIT PAMINAL POLRES SUMEDANG POLDA JAWA BARAT|POLRES SUMEDANG
KANIT PAMINAL POLRES TASIKMALAYA POLDA JAWA BARAT|POLRES TASIKMALAYA
KANIT PAMINAL POLRESTA CIREBON POLDA JAWA BARAT|POLRESTA CIREBON
KANIT PROVOS POLRES BOGOR POLDA JAWA BARAT|POLRES BOGOR
KANIT PROVOS POLRES CIAMIS POLDA JAWA BARAT|POLRES CIAMIS
KANIT PROVOS POLRES CIANJUR POLDA JAWA BARAT|POLRES CIANJUR
KANIT PROVOS POLRES GARUT POLDA JAWA BARAT|POLRES GARUT
KANIT PROVOS POLRES KARAWANG POLDA JAWA BARAT|POLRES KARAWANG
KANIT PROVOS POLRES PURWAKARTA POLDA JAWA BARAT|POLRES PURWAKARTA
KANIT PROVOS POLRES SUMEDANG POLDA JAWA BARAT|POLRES SUMEDANG
KANIT PROVOS POLRES TASIKMALAYA POLDA JAWA BARAT|POLRES TASIKMALAYA
KANIT PROVOS POLRESTA BOGOR KOTA POLDA JAWA BARAT|POLRESTA BOGOR KOTA
KANIT WABPROF POLRES BOGOR POLDA JAWA BARAT|POLRES BOGOR
KASIPROPAM POLRES BANJAR KOTA POLDA JAWA BARAT|POLRES BANJAR KOTA
KASIPROPAM POLRES BOGOR POLDA JAWA BARAT|POLRES BOGOR
KASIPROPAM POLRES CIAMIS POLDA JAWA BARAT|POLRES CIAMIS
KASIPROPAM POLRES CIMAHI POLDA JAWA BARAT|POLRES CIMAHI
KASIPROPAM POLRES GARUT POLDA JAWA BARAT|POLRES GARUT
KASIPROPAM POLRES INDRAMAYU POLDA JAWA BARAT|POLRES INDRAMAYU
KASIPROPAM POLRES KARAWANG POLDA JAWA BARAT|POLRES KARAWANG
KASIPROPAM POLRES KUNINGAN POLDA JAWA BARAT|POLRES KUNINGAN
KASIPROPAM POLRES MAJALENGKA POLDA JAWA BARAT|POLRES MAJALENGKA
KASIPROPAM POLRES PANGANDARAN POLDA JAWA BARAT|POLRES PANGANDARAN
KASIPROPAM POLRES SUBANG POLDA JAWA BARAT|POLRES SUBANG
KASIPROPAM POLRES SUKABUMI KOTA POLDA JAWA BARAT|POLRES SUKABUMI KOTA
KASIPROPAM POLRES SUKABUMI POLDA JAWA BARAT|POLRES SUKABUMI
KASIPROPAM POLRES SUMEDANG POLDA JAWA BARAT|POLRES SUMEDANG
KASIPROPAM POLRES TASIKMALAYA KOTA POLDA JAWA BARAT|POLRES TASIKMALAYA KOTA
KASIPROPAM POLRES TASIKMALAYA POLDA JAWA BARAT|POLRES TASIKMALAYA
KASIPROPAM POLRES TASIKMALAYA POLDA JAWA Barat|POLRES TASIKMALAYA
KASIPROPAM POLRESTA BOGOR KOTA POLDA JAWA BARAT|POLRESTA BOGOR KOTA
KASIPROPAM POLRESTA CIREBON POLDA JAWA BARAT|POLRESTA CIREBON
KAUR YANDUAN POLRES BOGOR POLDA JAWA BARAT|POLRES BOGOR
POLRES KAB. PANGANDARAN AKREDITOR|POLRES PANGANDARAN
POLRESTABES KOTA BANDUNG AKREDITOR|POLRESTABES BANDUNG
DIV PROPAM MABES POLRI|DIVPROPAM
POLDA JABAR DITLANTAS|SATKER LAIN`

const rows = []
for (const line of mappings.split('\n')) {
  const m = line.match(/^(.+?)\|(.+)$/)
  if (!m) continue
  rows.push({ id: uuidv4(), external_name: m[1].trim(), internal_unit: m[2].trim(), created_at: new Date().toISOString(), updated_at: new Date().toISOString() })
}

console.log(`Inserting ${rows.length} mappings directly to Supabase...`)

for (const row of rows) {
  const { error } = await supabase.from('unit_mapping').upsert(row, { onConflict: 'id' })
  if (error) { console.error(`FAIL ${row.external_name}:`, error.message) }
}

const { count } = await supabase.from('unit_mapping').select('*', { count: 'exact', head: true })
console.log(`Total in DB: ${count}`)
