// Status constants for the new status model (Wave 4, Todo 24)
// Pure constants module — no imports from other project files

export const STATUS = {
  SURAT_MASUK_POLDA_JABAR: 'Surat Masuk Polda Jabar',
  DISPOSISI_PIMPINAN: 'Disposisi Pimpinan',
  PENYELIDIKAN_PAMINAL: 'Penyelidikan Paminal',
  PENYELIDIKAN_PROVOS: 'Penyelidikan Provos',
  SIDANG_DISIPLIN: 'Sidang Disiplin',
  LIMPAH_PAMINAL_PROVOS: 'Limpah Paminal ke Provos',
  SELESAI: 'Selesai',
}

export const RESOLUSI = {
  PERDAMAIAN: 'Perdamaian',
  RJ: 'RJ',
  TERBUKTI: 'Terbukti',
  TIDAK_TERBUKTI: 'Tidak Terbukti',
}

export const BUCKET = {
  SURAT_MASUK: [STATUS.SURAT_MASUK_POLDA_JABAR],
  DALAM_PENANGANAN: [
    STATUS.DISPOSISI_PIMPINAN,
    STATUS.PENYELIDIKAN_PAMINAL,
    STATUS.PENYELIDIKAN_PROVOS,
    STATUS.SIDANG_DISIPLIN,
    STATUS.LIMPAH_PAMINAL_PROVOS,
  ],
  SELESAI: [STATUS.SELESAI],
}

export const STATUS_TRANSITIONS = {
  [STATUS.SURAT_MASUK_POLDA_JABAR]: [STATUS.DISPOSISI_PIMPINAN, STATUS.SELESAI],
  [STATUS.DISPOSISI_PIMPINAN]: [STATUS.PENYELIDIKAN_PAMINAL, STATUS.SELESAI],
  [STATUS.PENYELIDIKAN_PAMINAL]: [STATUS.PENYELIDIKAN_PROVOS, STATUS.LIMPAH_PAMINAL_PROVOS, STATUS.SELESAI],
  [STATUS.PENYELIDIKAN_PROVOS]: [STATUS.SIDANG_DISIPLIN, STATUS.SELESAI],
  [STATUS.SIDANG_DISIPLIN]: [STATUS.SELESAI],
  [STATUS.LIMPAH_PAMINAL_PROVOS]: [STATUS.PENYELIDIKAN_PROVOS, STATUS.SELESAI],
  [STATUS.SELESAI]: [],
}

// PERDAMAIAN and RJ are allowed at ALL stages EXCEPT SIDANG_DISIPLIN
export const RESOLUSI_ALLOWED = {
  [STATUS.SURAT_MASUK_POLDA_JABAR]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ, RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.DISPOSISI_PIMPINAN]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ, RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.PENYELIDIKAN_PAMINAL]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ, RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.PENYELIDIKAN_PROVOS]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ, RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.SIDANG_DISIPLIN]: [RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.LIMPAH_PAMINAL_PROVOS]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ, RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.SELESAI]: [],
}

export function getBucket(status) {
  if (BUCKET.SURAT_MASUK.includes(status)) return 'SURAT_MASUK'
  if (BUCKET.DALAM_PENANGANAN.includes(status)) return 'DALAM_PENANGANAN'
  if (BUCKET.SELESAI.includes(status)) return 'SELESAI'
  return null
}

export function canTransition(from, to) {
  const allowed = STATUS_TRANSITIONS[from]
  if (!allowed) return false
  return allowed.includes(to)
}

export function canResolve(status, resolusi) {
  const allowed = RESOLUSI_ALLOWED[status]
  if (!allowed) return false
  return allowed.includes(resolusi)
}
