export const STATUS = {
  SURAT_MASUK_POLDA_JABAR: 'Surat Masuk Polda Jabar',
  DISPOSISI_PIMPINAN: 'Disposisi Pimpinan',
  PENYELIDIKAN_PAMINAL: 'Penyelidikan Paminal',
  PENYELIDIKAN_PROVOS: 'Penyelidikan Provos',
  PEMERIKSAAN_GARPLIN: 'Pemeriksaan/Pemberkasan GARPLIN',
  PEMERIKSAAN_GAR_KEPP: 'Pemeriksaan/Pemberkasan GAR KEPP',
  SIDANG_DISIPLIN: 'Sidang Disiplin',
  SIDANG_KKE: 'Sidang KKE',
  LIMPAH_PAMINAL_PROVOS: 'Limpah Paminal ke Provos',
  PUTUSAN_SIDANG: 'Putusan Sidang',
  SELESAI: 'Selesai',
}

export const RESOLUSI = {
  PERDAMAIAN: 'Perdamaian',
  RJ: 'RJ',
  TERBUKTI: 'Terbukti',
  TIDAK_TERBUKTI: 'Tidak Terbukti',
}

export const BUCKET = {
  SURAT_MASUK: [STATUS.SURAT_MASUK_POLDA_JABAR],
  DALAM_PENANGANAN: [
    STATUS.DISPOSISI_PIMPINAN,
    STATUS.PENYELIDIKAN_PAMINAL,
    STATUS.PENYELIDIKAN_PROVOS,
    STATUS.PEMERIKSAAN_GARPLIN,
    STATUS.PEMERIKSAAN_GAR_KEPP,
    STATUS.SIDANG_DISIPLIN,
    STATUS.SIDANG_KKE,
    STATUS.LIMPAH_PAMINAL_PROVOS,
    STATUS.PUTUSAN_SIDANG,
  ],
  SELESAI: [STATUS.SELESAI],
}

export const STATUS_TRANSITIONS = {
  [STATUS.SURAT_MASUK_POLDA_JABAR]: [STATUS.DISPOSISI_PIMPINAN, STATUS.SELESAI],
  [STATUS.DISPOSISI_PIMPINAN]: [STATUS.PENYELIDIKAN_PAMINAL, STATUS.PENYELIDIKAN_PROVOS, STATUS.SELESAI],
  [STATUS.PENYELIDIKAN_PAMINAL]: [STATUS.PEMERIKSAAN_GARPLIN, STATUS.LIMPAH_PAMINAL_PROVOS, STATUS.SELESAI],
  [STATUS.PENYELIDIKAN_PROVOS]: [STATUS.PEMERIKSAAN_GARPLIN, STATUS.PEMERIKSAAN_GAR_KEPP, STATUS.SELESAI],
  [STATUS.PEMERIKSAAN_GARPLIN]: [STATUS.SIDANG_DISIPLIN, STATUS.SELESAI],
  [STATUS.PEMERIKSAAN_GAR_KEPP]: [STATUS.SIDANG_KKE, STATUS.SELESAI],
  [STATUS.SIDANG_DISIPLIN]: [STATUS.PUTUSAN_SIDANG, STATUS.SELESAI],
  [STATUS.SIDANG_KKE]: [STATUS.PUTUSAN_SIDANG, STATUS.SELESAI],
  [STATUS.LIMPAH_PAMINAL_PROVOS]: [STATUS.PENYELIDIKAN_PROVOS, STATUS.SELESAI],
  [STATUS.PUTUSAN_SIDANG]: [STATUS.SELESAI],
  [STATUS.SELESAI]: [],
}

// PERDAMAIAN and RJ allowed from Surat Masuk s/d Pemberkasan (before sidang)
export const RESOLUSI_ALLOWED = {
  [STATUS.SURAT_MASUK_POLDA_JABAR]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.DISPOSISI_PIMPINAN]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.PENYELIDIKAN_PAMINAL]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.PENYELIDIKAN_PROVOS]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.PEMERIKSAAN_GARPLIN]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.PEMERIKSAAN_GAR_KEPP]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.SIDANG_DISIPLIN]: [RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.SIDANG_KKE]: [RESOLUSI.TERBUKTI, RESOLUSI.TIDAK_TERBUKTI],
  [STATUS.LIMPAH_PAMINAL_PROVOS]: [RESOLUSI.PERDAMAIAN, RESOLUSI.RJ],
  [STATUS.PUTUSAN_SIDANG]: [],
  [STATUS.SELESAI]: [],
}

export const SIMPLIFIED_STATUSES = ['DITERIMA', 'DALAM PROSES', 'PROSES SIDANG', 'TERBUKTI', 'TIDAK TERBUKTI', 'PERDAMAIAN']

export function getBucket(status) {
  if (BUCKET.SURAT_MASUK.includes(status)) return 'SURAT_MASUK'
  if (BUCKET.DALAM_PENANGANAN.includes(status)) return 'DALAM_PENANGANAN'
  if (BUCKET.SELESAI.includes(status)) return 'SELESAI'
  return null
}

export function canTransition(from, to) {
  const allowed = STATUS_TRANSITIONS[from]
  if (!allowed) return false
  return allowed.includes(to)
}

export function canResolve(status, resolusi) {
  const allowed = RESOLUSI_ALLOWED[status]
  if (!allowed) return false
  return allowed.includes(resolusi)
}
