// Short label for display in badges
export function shortUnit(u) {
  if (!u) return '-'
  return u
    .replace(' SUBBID PAMINAL POLDA JAWA BARAT', ' PAMINAL')
    .replace(' POLDA JAWA BARAT', '')
}

// Category list - full set discovered from live Paminal cases
export const CATEGORY_OPTIONS = [
  'Penanganan Perkara Pidana',
  'Pelayanan Kepolisian',
  'PERILAKU & INTEGRITAS PERSONAL',
  'Pelanggaran Hukum / Tindak Pidana',
  'PERSELINGKUHAN / HUBUNGAN TERLARANG',
  'DISKRIMINASI DALAM PELAYANAN KEPOLISIAN',
  'ASUSILA',
  'PENYALAHGUNAAN WEWENANG',
  'PENYALAHGUNAAN WEWENANG DALAM KEGIATAN OPERASIONAL',
  'AROGANSI SOSIAL / SIKAP MERENDAHKAN ORANG LAIN',
  'INTIMIDASI VERBAL',
  'WANPRESTASI DALAM PERJANJIAN PRIBADI',
  'PENGGELAPAN',
  'PENIPUAN / FRAUD',
  'PENYITAAN TANPA SURAT ATAU PROSEDUR SAH',
  'MEMINTA ATAU MENERIMA IMBALAN DI LUAR KETENTUAN PELAYANAN PUBLIK',
]
